name: "CI"
on:
  push:
    branches: [ "master" ]
  pull_request:
  schedule:
    # Everyday at 4:00 AM
    - cron: "0 4 * * *"

jobs:
  build-test-documentation:
    name: Build, test & documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.1
      with:
        repository: input-output-hk/hydra-poc
        token: ${{ secrets.MY_TOKEN || github.token }}

    - name: Prepare nix
      uses: cachix/install-nix-action@v13
      with:
        skip_adding_nixpkgs_channel: true
        extra_nix_config: |
          trusted-public-keys = iohk.cachix.org-1:DpRUyj7h7V830dp/i6Nti+NEO2/nhblbov/8MW7Rqoo= hydra.iohk.io:f/Ea+s+dFdN+3Y/G+FDgSq+a5NEWhJGzdjvKNGv0/EQ= cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
          substituters = https://cache.nixos.org https://hydra.iohk.io https://iohk.cachix.org

    - name: Cachix cache of nix derivations
      uses: cachix/cachix-action@v10
      with:
        name: hydra-node
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'

    - name: Github cache ~/.cabal/packages, ~/.cabal/store and dist-newstyle
      uses: actions/cache@v2.1.5
      with:
        path: |
          ~/.cabal/packages
          ~/.cabal/store
          dist-newstyle
        key: |
          cabal-${{ runner.os }}-${{ hashFiles('cabal.project', 'default.nix', 'shell.nix') }}

    - name: Prepare nix-shell
      run: |
        nix-build shell.nix

    - name: Build
      run: nix-shell --pure --run '.github/workflows/ci-build.sh'

    - name: Test
      run: nix-shell --pure --run '.github/workflows/ci-test.sh'
      # https://giters.com/gfx/example-github-actions-with-tty
      # The default shell does not allocate a TTY which breaks some tests
      shell: 'script -q -e -c "bash {0}"'
      env:
        TERM: "xterm"

    - name: Documentation (Haddock)
      run: |
        nix-shell --pure --run '.github/workflows/ci-haddock.sh'

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'
        cache-dependency-path: docs/yarn.lock

    - name: Documentation (Docusaurus)
      working-directory: docs
      run: |
        yarn && yarn build
        mkdir -p public/head-protocol
        mv build/* public/head-protocol
        echo "hydra.family" > public/CNAME

    - name: Publish Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v1
      with:
        files: ./**/test-results.xml

    - name: Publish Documentation
      if: github.event_name == 'push'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN || github.token }}
        publish_dir: docs/public
        enable_jekyll: true
        force_orphan: true

  markdown-link-check:
    name: "Check markdown links"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    # NOTE: We do not check the 'docs' folder because links in markdown are already checked and handled by Docusaurus.
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        folder-path: "hydra-cardano-api, hydra-cluster, hydra-node, hydra-plutus, hydra-prelude, hydra-test-utils, hydra-tui, plutus-cbor, plutus-merkle-tree"
    - uses: gaurav-nelson/github-action-markdown-link-check@v1
      with:
        folder-path: "."
        max-depth: 1
